export const LOAD_COMPANY_FULFILLED = 'LOAD_COMPANY_FULFILLED';
export const LOAD_COMPANY_PENDING = 'LOAD_COMPANY_PENDING';
export const LOAD_NUMBERS_FULFILLED = 'LOAD_NUMBERS_FULFILLED';
export const LOAD_NUMBERS_PENDING = 'LOAD_NUMBERS_PENDING';

