export const LOAD_COMPANY_FULFILLED = 'LOAD_COMPANY_FULFILLED';
export const LOAD_COMPANY_PENDING = 'LOAD_COMPANY_PENDING';
export const LOAD_NUMBERS_FULFILLED = 'LOAD_NUMBERS_FULFILLED';
export const LOAD_NUMBERS_PENDING = 'LOAD_NUMBERS_PENDING';
export const VERIFY_NUMBER_FULFILLED = 'VERIFY_NUMBER_FULFILLED';
export const VERIFY_NUMBER_PENDING = 'VERIFY_NUMBER_PENDING';

